### ISSUE TITLE
Getting no function clause matching in Exzeitable.HTML.Search.build/1 when trying to build a table

### ISSUE THREAD

**Issue by mja00** [alanvardy/exzeitable#293] opened 2021-08-11 00:21 UTC
**Describe the bug**
When using the example code in the readme I get `no function clause matching in Exzeitable.HTML.Search.build/1` whenever I try to render the page. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow example code to create a table replacing all needed information with what is needed
2. Navigate to page
3. Get error

**Expected behaviour**
Page draws table

**Screenshots**
![image](https://user-images.githubusercontent.com/11252574/128951176-b727aa2f-03de-4337-8cc1-2f6fef2be6a0.png)

**Additional context**
Below is the code in my live_view module. 
```elixir
defmodule GlimeshWeb.GctLive.Components.AuditLogTableNew do

  alias GlimeshWeb.Router.Helpers, as: Routes
  import Ecto.Query

  use Exzeitable,
    # Required
    repo: Glimesh.Repo,
    routes: Routes,
    path: :gct_path,
    query: from(a in Glimesh.CommunityTeam.AuditLog),
    fields: [
      target: [label: "Target"]
    ]


  # The callback that renders your table
  def render(assigns) do
    ~L"""
    <%= build_table(assigns) %>
    """
  end
end
```

**Comment by alanvardy** [comment] 2021-08-19 18:31
Thank you for the bug report @mja00! On first look it seems like adding the `:debounce` option to your `use Exzeitable` call could resolve the issue.

I will look into this in the next couple of days and keep you updated :)

**Comment by mja00** [comment] 2021-08-19 18:33
I did have it there from the beginning, I was basically just pasting the example in and changing the needed vars, and it was still throwing that error. It looks like for some reason the assigns aren't being assigned so it can't build it for some reason.

**Comment by alanvardy** [comment] 2021-08-21 18:02
I'm having trouble reproducing this on my end @mja00, I see that this is for an open source project. Would you be able to push this code up to a branch so I can walk though it?

**Comment by mja00** [comment] 2021-08-21 18:03
Sure thing. I'll get a branch with it running and send a message once it's up.

**Comment by atavistock** [comment] 2022-05-01 03:28
I'm seeing the same, with or without `debounce` set in the use keywords.

**Comment by alanvardy** [comment] 2022-05-02 19:28
I'll take a look, are you able to provide a reproducible example @atavistock ?

**Comment by atavistock** [comment] 2022-05-02 23:45
It seems to be because of https://github.com/alanvardy/exzeitable/issues/374

`debounce` never gets into assigns, it also looks like other assigns from the Exzeitable mount are missing.

**Comment by alanvardy** [comment] 2022-05-14 01:03
Resolved with https://github.com/alanvardy/exzeitable/pull/377

**Closed by alanvardy** 2022-05-14 01:03 UTC
Labels: bug
